### ISSUE TITLE
0.10.0 release checklist 

### ISSUE THREAD

**Issue by patrickjahns** [owncloud/user_ldap#140]
### Reason

- Improved user sync performance (duration & reliability) #125
- Improved caching logic to reduce load on LDAP #125
- don't set false quota #137 #127 
- Fixes to working with LDAP replica servers #138 
- Fixes related to Exception handling #139 
- Fixes trimming of binary uuids #146
- Fixes bind result for wrong password #149 
- Fixes syncing display names upon login #157

### QA

- [x] Create release branch -> `release/0.10.0` (by patrickjahns)
- [x] Create TestPlan https://github.com/owncloud/user_ldap/issues/150
- [x] Test and document in testplan => Final "Go" from QA (set 'QA-ready' label)

#### Testing Scenarios
This PR changes the way that we query LDAP for metadata - both through `user:sync` and on login. For this release, we must check that the metadata is correctly updated through both of these code paths. The following scenarios should be tested:

Both through `user:sync` and on login
 - [x] User that doesnt exist anymore on LDAP
 - [x] User that has missing critical attributes (like email, or displayname)
 - [x] User that has crazy quota attributes (0, null, false, true, f92ensfswewf)
 - [x] User that has multi value attributes (mail)
 - [x] User that has a multi value attribute as user search attribute (should all be loaded into the terms table)
 - [x] Test an existing SAML user to see if their values are updated on login

### Marketing

- [x]  Check/adapt info.xml stuff https://github.com/owncloud/user_ldap/pull/161
- [x]  Check/adapt screenshot https://github.com/owncloud/user_ldap/pull/161
- [x]  Blog post or other communication if applicable - to follow in Jan @lefherz @tomneedham

### Documentation
 - [ ] Changes in the docs needed?

### Build & Marketplace release

- [x]  Bump version in info.xml #144
- [x] Update CHANGELOG.md
- [x]  Sign and build tarball
- [x]  Upload to marketplace
- [x]  Rename QA milestone to '$version'
- [x]  Change CHANGELOG.md 'Unreleased' to '$version' and add a new 'Unreleased' section
- [x]  create PR with changes from release branch to `master`

Blockers:
~~#146~~
~~#149~~

**Comment by patrickjahns** [comment]
@tomneedham @butonic 
any changes for documentation needed for this release?

**Comment by butonic** [comment]
@patrickjahns hm, the apps inner workings have completely changed. And while it has been tested in several installations we should probably ask for more feedback.

**Comment by tomneedham** [comment]
public beta?

**Comment by butonic** [comment]
saml updates require https://github.com/owncloud/user_shibboleth/pull/207

**Comment by pmaier1** [comment]
Marketing stuff PR https://github.com/owncloud/user_ldap/pull/161

**Comment by felixboehm** [comment]
screenshot will be improved with next release

**Comment by DeepDiver1975** [comment]
there was a screenshot logog uploaded some month back - https://github.com/owncloud/screenshots/blob/master/user_ldap/owncloud-app-ldap.jpg

take than? @felixboehm @pmaier1 @hurradieweltgehtunter

**Comment by lefherz** [comment]
we already did social announcement. blog and mailing will follow in January.

**Comment by felixboehm** [comment]
leaving open for @patrickjahns to validate and close

**Comment by lefherz** [comment]
@patrickjahns https://owncloud.org/news/owncloud-refactored-ldap-app-brings-significantly-improved-sync-performance/

Communication is done :)

**Comment by patrickjahns** [comment]
Awesome - thanks guys for the great work - closing now
