### ISSUE TITLE
Add occ command acceptance tests

### ISSUE THREAD

**Issue by phil-davis** [owncloud/user_ldap#292]
``cli`` acceptance tests now exist in core.

General QA issue https://github.com/owncloud/QA/issues/570

- [x] check that extra non-LDAP local users and groups can be created, modified, deleted. #337 
- [x] check that LDAP-defined users can be deleted locally, but can "come back" again (because they are synced from LDAP) #337
- [x] check that LDAP-defined groups can be deleted locally, but can "come back" again (because they are synced from LDAP) #342 
- [x] check what can/cannot happen with respect to modifying attributes of LDAP users using occ commands #341
(clues in comment https://github.com/owncloud/core/pull/32731#issuecomment-428204236 )

**Comment by phil-davis** [comment]
Also review what Provisioning API and webUI acceptance tests for LDAP-specific cases already exist, and add scenarios to fill out coverage of the items above.

**Comment by dpakach** [comment]
Completed in PRs #337 , #341, #342
