### ISSUE TITLE
Standardize makefile and drone stuffs

### ISSUE THREAD

**Issue by skshetry** [owncloud/user_ldap#330]
The PR #321 standardized makefile and drone, but still leaves a lot to fix. The following are the fixes that we currently need to address:

- [x] Set `composer_deps` and `composer_dev_deps` to nothing. #330
- [x] Remove use of `composer_deps` and `composer_dev_deps`. #330
- [x] Set new `help` target and add help message #330
- [x] Remove `$(COMPOSER_BIN)` (doesnot work anyway due to PR #328 ) #330
- [ ] Skip tests using `BEHAT_FILTER_TAGS` rather than using makefile - see comment https://github.com/owncloud/user_ldap/issues/330#issuecomment-479744777
- [x] Refactor drone for testing core's acceptance and apps' acceptance, as done in `encryption`, i.e. do not make separate `test-acceptance-ldap`. #330
- [x] Remove use of `TEST_SOURCE`, use `TEST_SUITE`. #330
- [x] Do not run `selenium` on api tests. (seemed already done)
- [x] Setup server on drone when `NEED_SERVER` is `true`, not on `TEST_SUITE: acceptance`. (seemed already done)

**Comment by ownclouders** [comment]
[GitMate.io](https://gitmate.io) thinks the contributors most likely able to help are @individual-it, and @phil-davis.

Possibly related issues are https://github.com/owncloud/user_ldap/pull/302 (Add more tests to drone), https://github.com/owncloud/user_ldap/issues/316 (Standardize CI infrastructure), https://github.com/owncloud/user_ldap/pull/321 ([WIP] Standardize CI setup), https://github.com/owncloud/user_ldap/issues/273 (Move remaining CI from Travis to drone), and https://github.com/owncloud/user_ldap/pull/328 (Remove phar and make it more standardized).

**Comment by phil-davis** [comment]
Note to self: probably a lot of the items have been done. Hopefully I just need to review the latest `.drone.yml` and `Makefile` and tick off the list :)

**Comment by phil-davis** [comment]
@individual-it and I discussed about "Skip tests using BEHAT_FILTER_TAGS rather than using makefile"
It seems better the way it is now - for example `make test-acceptance-core-api` knows in the make file what is the correct set of tags to use for selecting the core test scenarios that are appropriate to run in the LDAP case. So a developer can use the provided `make` target to "just run the tests" without having to think about manually specifying the "magic" tags.
