### ISSUE TITLE
LDAP 0.14.0

### ISSUE THREAD

**Issue by PVince81** [owncloud/user_ldap#377]
When taking care of a task (and marking as done), please add your name to the task!

### Reason
- [x] Add network timeout https://github.com/owncloud/user_ldap/issues/324 
- [x] Allow avatars to be changed by users if not provided by LDAP - [#188](https://github.com/owncloud/user_ldap/issues/188)
- [x] Remove PHP 5.6 support - [#388](https://github.com/owncloud/user_ldap/issues/388)
- [x] ~LDAP configuration is now stored JSON encoded - [#393](https://github.com/owncloud/user_ldap/issues/393)~ reverted for this release 
- [x] Clean up Application initialization code - [#396](https://github.com/owncloud/user_ldap/issues/396)
- [x] Remove unused use statements - [#399](https://github.com/owncloud/user_ldap/issues/399) [#400](https://github.com/owncloud/user_ldap/issues/400)
- [x] Do not return unavailable users - [#12](https://github.com/owncloud/user_ldap/issues/12)
- [x] Fix paging when limit is used - [#315](https://github.com/owncloud/user_ldap/issues/315)
- [x] Reuse existing LDAP accounts if available https://github.com/owncloud/user_ldap/pull/165
- [x] Replace magic numbers with constants https://github.com/owncloud/user_ldap/pull/435
- [x] Log bind errors https://github.com/owncloud/user_ldap/pull/436
- [x] Simplify connection: Get rid of init method https://github.com/owncloud/user_ldap/pull/437

### QA

- [x] Create **QA Milestone**
- [x] Move items from `development` to `qa` @davitol 
- [x] Create release branch with the format "release-0.14.0" @patrickjahns  
- [x] Create "0.14.0 Testplan" @davitol https://github.com/owncloud/user_ldap/issues/446
- [x] Test and document in testplan => Final "Go" from QA (set 'QA-ready' label) @davitol 

### Documentation

- [ ] Changes in the docs needed?

### Marketing

- [ ] Ping RocketChat channel #marketing
- [x] Check/adapt info.xml stuff
- [ ] Check/adapt screenshot
- [ ] Blog post or other communication if applicable

### Build

All actions to be done on the release branch from here:
- [x] Bump version in info.xml (no version suffix)
- [x] Update CHANGELOG.md - Change CHANGELOG.md 'Unreleased' to '$version' (final release date unknown)

#### Beta/RC

- [x] Create github tag for 'v${version}RC1' on release branch
- [x] Build and sign RC tarball from github tag 'v${version}RC1' (see
  handbook for how to build)
- [x] Upload as Github release using changelog entries
- [x] Test and document in testplan => Final "Go" from QA (set 'QA-ready' label) => else do another RC after fixing issues in the "release-$version" branch @davitol 

#### Final

- [x] Create github tag for final 'v${version}' on release branch
- [x] Build and sign final tarball from github tag 'v${version}' (see
  handbook for how to build)
- [x] Upload as Github release using changelog entries
- [x] Smoke test tarball (at least install + enable) @davitol 

### Publishing

- [x] Upload tarball to marketplace (see handbook for details)
- [x] Publish tarball for customers (see handbook for details)
- [x] Send mail to release-coordination with link to this ticket and to the changelog

### Post-release

- [x] Rename QA milestone to '$version'
- [x] Add a new 'Unreleased' section in CHANGELOG.md and add release date '$version - $currentDate' (ex: 3.1.5 - 2018-08-01)
- [x] Create PR to merge changes back to the `master` branch with
  description "Closes #XYZ" with the release ticket number

**Comment by ownclouders** [comment]
[GitMate.io](https://gitmate.io) thinks possibly related issues are https://github.com/owncloud/user_ldap/issues/296 (Tracking results for LDAP 0.12.0), https://github.com/owncloud/user_ldap/issues/97 ([10.0.0] Show disable users -- ldap:check-user??), https://github.com/owncloud/user_ldap/pull/303 (Release 0.12.0), https://github.com/owncloud/user_ldap/pull/325 (Release 0.13.0), and https://github.com/owncloud/user_ldap/issues/252 (LDAP 0.12.0 release).

**Comment by PVince81** [comment]
- [ ] clarify change of behavior:
    - [ ] config is now JSON, is this ok for support ?
    - [ ] "do not return not available users" need better wording, evaluate if admins need to be notified to double check their LDAP filters to avoid potential service disruption

@jvillafanez @cdamken @pako81 FYI

**Comment by PVince81** [comment]
- [ ] might want to branch off old tag to avoid PHP 5.6 deprecation that early

**Comment by pmaier1** [comment]
We added #165 to the reasons. Please include this PR @micbar.

**Comment by VicDeo** [comment]
>"do not return not available users" need better wording, evaluate if admins need to be notified to double check their LDAP filters to avoid potential service disruption

what about "Validate group members against user filter"? If I'm not mistaken this is exactly what https://github.com/owncloud/user_ldap/issues/12 does

**Comment by davitol** [comment]
@micbar user_ldap-0.14.0RC1 tarball is QA-ready

**Comment by phil-davis** [comment]
Note: when we try to "merge release-0.14.0 branch back to master" we are going to have to be careful, because actually we do not want to merge back:
PR #449 "hotfix" that was just to keep some compatibility ffor this release with core 10.2.1
PR #466 the last commit that disables running `phan` in CI (phan runs just fine in master)
and ...?
