### ISSUE TITLE
user_ldap 0.15.1

### ISSUE THREAD

**Issue by HanaGemela** [owncloud/user_ldap#528]
### Reason

- [x] Release needed for https://github.com/owncloud/user_ldap/pull/490
- [x] Easier tls - [#512](https://github.com/owncloud/user_ldap/issues/512)

### QA

- [x] Generate Changelog
- [x] Create **QA** Milestone and set the description to $version
- [x] Move items from `development` to `qa`
- [x] Create release branch with the format "release-$version"
- [x] Create "user ldap 0.15.1" TestPlan @davitol  https://github.com/owncloud/user_ldap/issues/535

### Documentation

- [x] Changes in the docs needed? If so create issue in owncloud/docs. https://github.com/owncloud/docs/issues/2425

### Marketing

- [x] Ping @owncloud/marketing
- [x] Ping pmaier to check `info.xml` description and screenshot

### Build

All actions to be done on the release branch from here:
- [x] Bump version in `info.xml` (no version suffix)
- [x] Check php version dependency in `info.xml`
- [x] Check minimum ownCloud version dependency in `info.xml`
- [x] Change CHANGELOG.md 'Unreleased' to '$version' (today's date)

#### Beta/RC

- [x] Create github tag for `v${version}RC1` on release branch
- [x] Build and sign RC tarball from github tag `v${version}RC1` (see
  handbook for how to build)
- [x] Upload as Github release using changelog entries
- [x] Test and document in testplan => Final "Go" from QA (set 'QA-ready' label) => else do another RC after fixing issues in the "release-$version" branch

#### Final

- [x] Check that no documentation issues are pending https://github.com/owncloud/docs/issues/2425
- [x] Rename last RC tarball to final
- [x] Create github tag for final `v${version}` on release branch
- [x] Upload as Github release using changelog entries

### Publishing

- [x] Upload tarball to marketplace (see handbook for details)
- [x] Publish tarball for customers (see handbook for details) - https://customer.owncloud.com and https://portal.owncloud.com
- [x] Send mail to release-coordination with link to this ticket and to the changelog
- [x] Copy email to rocket chat `#updates` channel

### Post-release

- [x] Rename QA milestone to `$version`
- [x] Add a new 'Unreleased' section in CHANGELOG.md
- [x] Create PR to merge changes back to the `master` branch with
  description "Closes #XYZ" with the release ticket number
- [x] Close the milestone
- [x] Ensure [release template](https://github.com/owncloud/handbook/edit/master/modules/ROOT/examples/releases/server_app_release_template.md) is up to date

**Comment by HanaGemela** [comment]
@davitol RC1 for testing https://github.com/owncloud/user_ldap/releases/tag/v0.15.1RC1

**Comment by davitol** [comment]
Edited OP due to this version also includes - Easier tls - [#512](https://github.com/owncloud/user_ldap/issues/512)

**Comment by pmaier1** [comment]
> Edited OP due to this version also includes - Easier tls - #512

Doesn't this make it a minor release, e.g., 0.16?

**Comment by HanaGemela** [comment]
Raised the priority on @pmaier1's request

**Comment by davitol** [comment]
> Doesn't this make it a minor release, e.g., 0.16?

Yes, it could be consider as 0.16. if we say it is a new functionality but also it can be considered as a bugfix. So IMHO let's move forward as 0.15.1 and have the stuff out ASAP

**Comment by davitol** [comment]
@HanaGemela Tarball is QA-ready

> @davitol RC1 for testing https://github.com/owncloud/user_ldap/releases/tag/v0.15.1RC1
