### ISSUE TITLE
Release User LDAP 0.15.4

### ISSUE THREAD

**Issue by phil-davis** [owncloud/user_ldap#605]
### Reason

- for PR #599 "Fixed read LDAP attribute value 0 returned as null" 
- ... and whatever else has been merged recently:
   -  Security: filter special characters from password field [#636](https://github.com/owncloud/user_ldap/issues/636)
   - LDAP multiple base dns break pagination [#307](https://github.com/owncloud/user_ldap/issues/307)
   - Add warning for disabling email login regarding strict login check [#581](https://github.com/owncloud/user_ldap/issues/581) (Requires 10.5.0)
   - Facelift [#597](https://github.com/owncloud/user_ldap/issues/597)

### Product approval 

- [x] Verify transifex commits are in master: If a folder https://github.com/owncloud/<APPNAME>/tree/master/l10n exists, then https://drone.owncloud.com/owncloud/<APPNAME> should receive nightly '[tx] updated from transifex` ...
- [x] Ping pmaier to check `info.xml` description and screenshot
- [x] Get approval on translations from pmaier - send the date of the last tx commit from drone to Patrick

### QA

- [x] Create **QA** Milestone and set the description to $version
- [x] Move tickets from milestone `development` to `qa` (testplan and tickets mentioned in release ticket)
- [x] Create release branch with the format "release-$version"
- [x] Create "$version Testplan" -> https://github.com/owncloud/user_ldap/issues/638
- [ ] copy new/reopened issues from the previous release ticket as 'Issues to review' below.
- [ ] check if [Non-normal Release Process](https://confluence.owncloud.com/display/OG/Apps+with+differences+in+release+process) applies, and adapt this checklist.

### Documentation

- [x] Changes in the docs needed? If so create issue in owncloud/docs. -> ttps://github.com/owncloud/docs/issues/3684

### Marketing

- [ ] Ping @owncloud/marketing
- [x] Update https://confluence.owncloud.com/display/PROD/Upcoming+Releases
- [x] Request a screenshot if the app is new or changed fundamentally

### Build

All actions to be done on the release branch from here:
- [x] Bump version in `info.xml` (no version suffix)
- [x] Check php version dependency in `info.xml`
- [x] Check minimum ownCloud version dependency in `info.xml`
- [x] Change CHANGELOG.md 'Unreleased' to '$version' (today's date)

#### Beta/RC

- [x] Ping product owner to create github tag for `v${version}-rc1` on release branch (see https://confluence.owncloud.com/display/EN/Product+Owners+List)
- [x] Build and sign RC tarball from github tag `v${version}-rc1` (see handbook for how to build)
- [x] Upload as Github release using changelog entries
- [x] Manual explorative testing:
    - [x] If this is an enterprise app: Enabling the app must start the grace period
    - [x] If this is the initial release of an app: Check that the minimum version constraint resolves correctly
    - [x] Changelog testing
    - [x] Test and document in testplan => Final "Go" from QA (set 'QA-ready' label) => else do another RC after fixing issues in the "release-$version" branch

#### Final

- [x] Check that no documentation issues are pending
- [x] Rename last RC tarball to final
- [x] Create github tag for final `v${version}` on release branch
- [x] Upload as Github release using changelog entries
- [x] Ping `#marketing` channel to coordinate publishing

### Publishing

- [x] Upload tarball to marketplace (see handbook in confluence for details)
- [x] Publish tarball for customers  - [old 10](https://customer.owncloud.com/owncloud/index.php/apps/files/?dir=%2FownCloud-Enterprise%2FownCloud-10), [old 10.0](https://customer.owncloud.com/owncloud/index.php/apps/files/?dir=%2FownCloud-Enterprise%2FownCloud-10-0)  and [new portal](https://portal.owncloud.com) (see [handbook](https://confluence.owncloud.com/display/OG/Releasing+Apps) for details)
- [ ] Send mail to release-coordination with link to this ticket and to the changelog
- [x] Copy email to rocket chat `#updates` channel

### Post-release

- [x] Add a new 'Unreleased' section in CHANGELOG.md (and also update links at the bottom!)
- [x] Create PR to merge changes back to the `master` branch with description "Closes #XYZ" with the release ticket number
- [ ] Rename QA milestone to `$version` and close the milestone
- [x] Update https://confluence.owncloud.com/display/PROD/Upcoming+Releases
- [x] Ensure [release template](https://github.com/owncloud/administration-internal/edit/master/tools/release/templates/server_app_release_template.md) is up to date
- [x] Ensure the testplan template ([community](https://github.com/owncloud/QA/tree/master/Server) is up to date. CREATE NEW FROM #638, deprecate https://github.com/owncloud/qa-enterprise/blob/master/Core/Test_plan_LDAP.md
- [x] Close the testplan issue

**Comment by C0rby** [comment]
https://gitea.owncloud.services/security/user_ldap/pulls/1 should be included into the next release

**Comment by jnweiger** [comment]
> https://gitea.owncloud.services/security/user_ldap/pulls/1 should be included into the next release
Did you see the comment from @butonic about the regexp?

We'll push forward with the 0.15.3 release in the next week. I'd love to see a PR for this!

**Comment by jnweiger** [comment]
@phil-davis the last 4 nightly builds for user_ldap failed. Is that random glitches, or something that needs fixing before we roll a release?

**Comment by phil-davis** [comment]
> @phil-davis the last 4 nightly builds for user_ldap failed. Is that random glitches, or something that needs fixing before we roll a release?

That was due  to some core changes to creating tags and related acceptance test changes that are not compatible with latest core 10.7.0. Fixed by https://github.com/owncloud/core/pull/38784 - I expect to see green CI this morning.

**Comment by C0rby** [comment]
> > https://gitea.owncloud.services/security/user_ldap/pulls/1 should be included into the next release
> > Did you see the comment from @butonic about the regexp?
> 
> We'll push forward with the 0.15.3 release in the next week. I'd love to see a PR for this!

I opened one here: https://github.com/owncloud/user_ldap/pull/636

**Comment by C0rby** [comment]
If it needs to go into a special branch I can redirect the PR.

**Comment by phil-davis** [comment]
> I expect to see green CI this morning.

@jnweiger CI was green for user_ldap last night - all good.

**Comment by micbar** [comment]
Ready to go into RC.

**Comment by jnweiger** [comment]
Release branch created. Tagged RC1.

**Comment by jnweiger** [comment]
## Issues opened while testing

* [ ] [QA] LDAP screenshot updates  https://github.com/owncloud/docs/issues/3684

**Comment by jnweiger** [comment]
QA pased with numerous non-blocker defects.

**Comment by jnweiger** [comment]
Late fix appears after 0.15.3 was pushed to marketplace: https://github.com/owncloud/user_ldap/pull/660

* [ ] tag as v0.15.4-RC1
* [ ] test with oauth2
* [ ] add oauth2 to the testplan
* [ ] release as v0.15.4 directly from the release-0.15.3 branch

**Comment by jnweiger** [comment]
https://github.com/owncloud/user_ldap/releases/tag/v0.15.4-rc2

**Comment by jnweiger** [comment]
Tests with core 10.8.0-rc1 passed. See https://github.com/owncloud/enterprise/issues/4508#issuecomment-883398925
