### ISSUE TITLE
Testplan for user_ldap 0.16.0

### ISSUE THREAD

**Issue by GeraldLeikam** [owncloud/user_ldap#682]
### Setup

<details><summary>Setup details (click to view)</summary>

* vi tasks/user_ldap.sh -> ldap_server=95.217.210.161 (small server from below)
* `bash ./make_oc10_apps.sh user_ldap=0.16.0-rc2 windows_network_drive oauth2`
  - https://oc1090beta1-ldap-0160-rc2-20211126.jw-qa.owncloud.works
* `bash ./make_oc10_apps.sh user_ldap=0.15.4 windows_network_drive oauth2` (for upgrade testing!)
  - https://oc1090beta1-ldap-0154-20211126.jw-qa.owncloud.works

#### OpenLDAP:

Prepare one LDAP backends for testing either of:
1. big server
   - 1200 users, 50 groups via releases/oc10/apps/ldap/genusers.py
   - three base DNs (we initially configure only one to owncloud)
   - nested groups

2. small ldap server
  - less than 1000 users, less than 40 groups
  - two base DNs (we initially configure only one to owncloud)

(outdated: https://github.com/owncloud/docker-servers/tree/owncloud-openldap)
</details>

### Upgrade

- [x] connect owncloud to ldap via previous release of user_ldap, 
   - [x] ldap users can log in
   - [x] upgrade user_ldap to current release candidate
   - [x] recurring ldap users can still log in.
   - [x] new first time ldap users can log in
- [x] connect owncloud to ldap via current release candidate
   - [x] ldap users can log in

### ldap:test-config

- [x] Run occ command ```ldap:test-config``` with a valid configID
   - [x] Access fine, The configuration is valid and the connection could be established!
- [x] Run occ command ```ldap:test-config``` with a wrong host
   - [x] (the host changed from a valid configuration) | Lost connection to LDAP server
- [x] Run occ command ```ldap:test-config``` with empty password
   - [x] The configuration is invalid. Please have a look at the logs for further details
- [x] Run occ command ```ldap:test-config``` with invalid configID
   - [x] ERROR: Invalid configID

### ldap:show-config

- [x] Run occ command ```ldap:show-config``` with no parameters
   - [x]  Show all configurations available | https://github.com/owncloud/user_ldap/issues/89
- [x] Run occ command ```ldap:show-config``` with valid configID
   - [x]  Show only the specified configuration
- [x] Run occ command ```ldap:show-config``` with invalid configID
   - [x]  ERROR: Invalid configID
- [x] Run occ command ```ldap:show-config``` with show-password flag
   - [x]  ldapAgentPassword shows the password in the result
- [x] Run occ command ```ldap:show-config``` without show-password flag
   - [x]  ldapAgentPassword hides the password in the result (uses “****”)

### ldap:set-config
- [x] Run occ command ```ldap:set-config``` with invalid configID
   - [x] ERROR: Invalid configID
- [x] Run occ command ```ldap:set-config``` with valid configID
   - [x] The config is set

### ldap:search

- [x] Run occ command ```ldap:search``` with valid configuration and longer limit
   - [x] Show results
- [x] Run occ command ```ldap:search``` with offset multiple of limit (both positive)
   - [x] Show results
- [x] Run occ command ```ldap:search```  name (default configuration)
   - [x] Show filtered results
- [x] Run occ command ```ldap:search``` name (fixed configuration – added “displayName” and/or other attributes in the User Search Attributes field in the wizard)
   - [x] Show filtered results
- [x] XXX Run occ command ```ldap:search --group``` group (fixed configuration – added “displayName” and/or other attributes in the Group Search Attributes field in the wizard)
   - [x]  Show filtered results
- [x] XXX Run occ command Group without search `occ ldap:search --group ''` 
   - [x] Show groups (currently 15 or less)

### ldap:check-user
- [x] Run occ command ```ldap:check-user``` with a good oC user id (the lengthy guuid string)
   - [x] Show success message
- [x] Run occ command ```ldap:check-user``` with a wrong oC user id
   - [x] ERROR: ldap user not recognized
- [x] Run occ command ```ldap:check-user``` with a good oC user id + disabled "Configuration Active" in Advanced->Connection settings
   - [x] ERROR: Cannot check user existence, because disabled LDAP configurations are present.
- [x] Run occ command ```ldap:check-user``` Good oc user id + all disabled configuration + force option; then enable the configuration and recheck
   - [x] Success message

### ldap:create-empty-config
- [x] Run occ command ```ldap:create-empty-config```
   - [x] Creates an empty LDAP configuration

### ldap:delete-config
- [x] Run occ command ```ldap:delete-config```
   - [x] Deletes an existing LDAP configuration

### user:sync
- [x] Run occ command ```sudo -u www-data ./occ user:sync "OCA\User_LDAP\User_Proxy"```
   - [x] This command syncs users stored in LDAP external backend service

### ldap:update-group
- [ ] ~Run occ command ```ldap:update-group```~ XXX Command no longer exists. obsoleted by user:sync
   - [ ] Update the specified group membership information stored locally

### Test LDAP properties
- [x] **email** Set a field as mail in advanced tab
   - [x] check that the mails are set with the right backend information in personal page for LDAP users
- [x] **avatar** Login with a user with an avatar field set in LDAP backend
   - [x] The avatar is shown instead of the username
- [x] **nested group** In advanced tab , check nested groups checkbox
   - [x]  In users page the nested group should appear with all the users of the subgroup
- [x] **internalUserAttribute** In expert tab , set an attribute as Internal Username
   - [x] The attribute is now used as internal Username

### User account table integration
- [x] Run ```occ user:sync -l```
   - [x]  list all known backend classes
- [x] Run ```occ user:sync "OCA\User_LDAP\User_Proxy"```
   - [x]  synchronize LDAP users from a given backend to the accounts table
- [x] Make changes in oC backend and ReRun ```occ user:sync "OCA\User_LDAP\User_Proxy"``` choosing disabling accounts option
   - [x]  Synchronize LDAP users from a given backend updated to the accounts table and disable the previous accounts
- [x] Make changes in oC backend and ReRun ```occ user:sync "OCA\User_LDAP\User_Proxy"``` choosing deleting accounts option
   - [x]  Synchronize LDAP users from a given backend updated to the accounts table and delete the previous accounts

### Wizard General

- [x] configuration: from valid config, change to a wrong url and change back to the good ones
   - [x]  configuration is shown as ok
- [x] user filter: choose one of the “only those object” select
   - [x]  Filter is correctly applied in the users page
- [x] login filter: checked with LDAP username (uid) and with LDAP email
   - [x]  users can login with both uid and email fields
- [x] More apps in the User authentication Panel
   - [x] `occ app:enable oauth2` -> The tabs do not overlap with user_ldap

### Wizard Configuration Users
- [x] 1. “Manually enter LDAP filters” is enabled <br> 2. The input field for manually writing LDAP filter is shown
(“raw mode”) <br> 3. Click on “Edit LDAP Query”
   - [x]  1. A Configuration Dialog is shown <br> 2. Subsqeuent action is coherent with button click (either switch or stay)
- [x] 1a. “Manually enter LDAP filters” is enabled and assisted mode is active <br> 1b. or “Manually enter LDAP filters” is disabled <br> 3. Click on “Edit LDAP Query”
   - [x]  1. Mode is toggled directly <br> 2. If assisted mode is activated for the first time, object class and groups detection is run once
- [x] 1. Be in Assisted Mode <br> 2. Open object class multiselect <br> 3. Change values up to your choice and close it
   - [x]  1. After closing, the LDAP filter is being updated (shown next to “LDAP Filter:”) <br> 2. The filter contains exactly all selected object classes
- [x] 1. Have the extended group selector <br> 2. Perform search with the search input field
   - [x]  1. According to the value entered groups are filtered correspondingly in both fields
- [x] XXX 1. Have the extended group selector <br> 2. Select one or more groups in the “available groups” list <br> 3. Click the “>” / "<" buttons
   - [x]  XXX The selected groups are *added* to / *removed* as expected. -> #700
- [x] 1. Have a properly set up filter <br> 2. Click on “Verify settings and count users”
   - [x]  1. A count is done, indicated by a spinner next to the button <br> 2. When done, a label appears saying “xx users found”, if more then 1000 users are available “> 1000 users found“ is shown
- [x] 1. Have a filter set up that does not return users <br> 2. Click on “Verify settings and count users”
   - [x]  1. A count is done, indicated by a spinner next to the button <br> 2. When done, a label appears saying “0 users found”

### Wizard Configuration groups
- [x] 1. Have other tabs completed correctly <br> 2. “Manually enter LDAP filters” is disabled <br> 3. Move to Groups tab
   - [x]  XXX 1. Detection for Object Classes and Groups is running <br> 2.If more than 40 groups available, a different group selection tool is presented (not the known multiselect) <br> 3. No filter is created initially, no text next to “LDAP Filter:”
- [x] 1. Have other tabs completed correctly <br> 2. “Manually enter LDAP filters” is enabled <br> 3. Move to Groups tab
   - [x]  1. A raw input field for the LDAP filter is presented. <br> 2. The multi select box elements are disabled <br> 3. i.e. Neither object classes nor groups are being detected
- [x] 1. “Manually enter LDAP filters” is enabled <br> 2. The input field for manually writing LDAP filter is shown
(“raw mode”) <br> 3. Click on “Edit LDAP Query”
   - [x]  1. A Configuration Dialog is shown <br> 2. Subsequent action is coherent with button click (either switch or stay)
- [x] 1a. “Manually enter LDAP filters” is enabled and assisted mode is active <br> 1b. or “Manually enter LDAP filters” is disabled <br> 3. Click on “Edit LDAP Query”
   - [x]  1. Mode is toggled directly <br> 2. If assisted mode is activated for the first time, object class and groups detection is run once
- [x] 1. Have a filter set up that does not return groups <br> 2. Click on “Verify settings and count groups”
   - [x]  1. A count is done, indicated by a spinner next to the button <br> 2. When done, a label appears saying “0 groups found”

### Wizard Configuration Advanced
- [x] 1. Have other tabs completed correctly <br> 2. Go to Advanced Tab <br> 3. Be in Connection Settings
   - [x]  1. See that configuration is active
- [ ] 1. Have other tabs completed correctly <br> 2. Go to Advanced Tab <br> 3. Open Directory Settings
   - [ ]  1. User Display Name field should be not displayName, but displayname (lowercase) or cn (due to auto-detection in the background) <br> 2. Group-Member-Associtation should be correct (depends on OpenLDAP, AD typically has “member (AD)”)
- [ ] 1. Have other tabs completed correctly <br> 2. Go to Advanced Tab <br> 3. Open Special Attributes
   - [ ]  1. “Email field” should be filled in (given that at least one user has mail or mailPrimaryAddress set, So that auto-detection can do its job)
- [x] 1. Click on “Test configuration”
   - [x]  1. A message will appear with the result of the Test

### Maintenance Commands
- [x] `occ ldap:invalidate-cache` XXX take no parameter `<user name>`
- [x] `occ group:list-members <group name>`
- [x] `occ user:list-groups <user id>`
- [x] `occ file:scan --group <group>`
- [ ] `occ background:queue:ex ...` TODO: find expected behacviour
- [x] `occ ldap:search --group ''`

**Comment by jnweiger** [comment]
## Changlog testing

- [ ] Change color of warning sign for expert settings [#678](https://github.com/owncloud/user_ldap/pull/678)
- [ ] Fix user group selection layout [#672](https://github.com/owncloud/user_ldap/pull/672)
- [ ] Add a command to invalidate the LDAP cache [#670](https://github.com/owncloud/user_ldap/pull/670)
- [ ] Adjust command description [#671](https://github.com/owncloud/user_ldap/pull/671)
- [ ] Drop PHP 7.2 in sonar-project.properties [#680](https://github.com/owncloud/user_ldap/pull/680)
- [ ] When checking memberof, apply the group filter after getting all groups [#683](https://github.com/owncloud/user_ldap/pull/683)

**Comment by jnweiger** [comment]
Testplan completed with minor issues (but more complete than ever before)

QA passed.

**Comment by jnweiger** [comment]
Release done. Testplan updates merged back to template. Closing.
