### ISSUE TITLE
Rewrite / improve LDAP wizard UX

### ISSUE THREAD

**Issue by PVince81** [owncloud/user_ldap#69]
Using this as a group ticket to gather multiple UX issues into one:
- [ ] dropdown scrolling issues: https://github.com/owncloud/core/issues/11444
- [ ] dropdown size issues: https://github.com/owncloud/core/issues/11446

- [ ] textbox width issues: https://github.com/owncloud/core/issues/16142
- [ ] status gauge inconsistency: https://github.com/owncloud/core/issues/24860
- [ ] useless arrows appearing: https://github.com/owncloud/core/issues/18955
- [ ] finger cursor issue: https://github.com/owncloud/core/issues/20345
- [ ] improve trash button behavior: https://github.com/owncloud/core/issues/16126
- [ ] hostname not shown: https://github.com/owncloud/core/issues/16231
- [ ] add group add arrow wrong behavior: https://github.com/owncloud/core/issues/16169
- [ ] configuration active checkbox location: https://github.com/owncloud/core/issues/16059

@jvillafanez @davitol FYI, let's add small/low UX issues from now on into this ticket instead of overflowing the bug tracker.

Then whoever is working on improving LDAP wizard UX could tackle most of these in one go.

**Comment by PVince81** [comment]
- [ ] disable buttons in edit LDAP query mode: https://github.com/owncloud/core/issues/16279
